"""Make dob nullable

Revision ID: 0e3dc215cfe0
Revises: f713c056cae5
Create Date: 2025-12-17 01:46:56.884210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3dc215cfe0'
down_revision: Union[str, Sequence[str], None] = 'f713c056cae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
