"""Update oauth_tokens and  users tables.

Revision ID: f713c056cae5
Revises: ae94b2ad76f3
Create Date: 2025-12-15 00:10:25.046794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f713c056cae5'
down_revision: Union[str, Sequence[str], None] = 'ae94b2ad76f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('oauth_tokens', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oauth_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('oauth_tokens', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_provider', 'oauth_tokens', ['user_id', 'provider'])
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_constraint('uq_user_provider', 'oauth_tokens', type_='unique')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.alter_column('oauth_tokens', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('oauth_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('oauth_tokens', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('oauth_tokens', 'scopes')
    # ### end Alembic commands ###
